"""initial schema

Revision ID: 8244c8da0f8f
Revises: 
Create Date: 2026-06-19 10:02:34.639471

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8244c8da0f8f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_lot_id'), 'audit_log', ['lot_id'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_budget', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('allocation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('config_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('config_snapshot_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pblntf_ty', sa.String(length=4), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_high_impact', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_ticker'), 'news_items', ['ticker'], unique=False)
    op.create_table('sentiment_state',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ewma_score', sa.Float(), nullable=False),
    sa.Column('half_life_hours', sa.Float(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('signals',
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime_pass', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=True),
    sa.Column('confirm_flags_json', sa.JSON(), nullable=False),
    sa.Column('indicator_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('news_ewma', sa.Float(), nullable=True),
    sa.Column('acted', sa.Boolean(), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('campaign_reports',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('end_cash', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('per_lot_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('positions',
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.String(length=8), nullable=False),
    sa.Column('qty_target', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('qty_filled', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('parent_signal_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_index(op.f('ix_positions_campaign_id'), 'positions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_positions_state'), 'positions', ['state'], unique=False)
    op.create_index(op.f('ix_positions_ticker'), 'positions', ['ticker'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True),
    sa.Column('tr_id', sa.String(length=16), nullable=True),
    sa.Column('ord_dvsn', sa.String(length=8), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['positions.lot_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_lot_id'), 'orders', ['lot_id'], unique=False)
    op.create_index(op.f('ix_orders_state'), 'orders', ['state'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('tax', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['positions.lot_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index(op.f('ix_trades_lot_id'), 'trades', ['lot_id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_table('fills',
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('tax', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['positions.lot_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('fill_id')
    )
    op.create_index(op.f('ix_fills_lot_id'), 'fills', ['lot_id'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_lot_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_lot_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_orders_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_lot_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_positions_ticker'), table_name='positions')
    op.drop_index(op.f('ix_positions_state'), table_name='positions')
    op.drop_index(op.f('ix_positions_campaign_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('campaign_reports')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('sentiment_state')
    op.drop_index(op.f('ix_news_items_ticker'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_lot_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
